/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobukuvero;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Az
 */
public class MasterBuku extends javax.swing.JFrame {

    DefaultTableModel tabel;
    DbBuku debe = new DbBuku();
    List<DbBuku> dataBuku = new ArrayList<>();

    /**
     * Creates new form MasterBuku
     */
    public MasterBuku() {
        initComponents();
        initTable();
        showTable();
        // Mode Operasi CRUD untuk tampilan
        operation(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUbah1 = new javax.swing.JButton();
        mode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputBukuId = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputBukuNama = new javax.swing.JTextField();
        inputBukuHarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        btnUbah1.setText("Cetak");
        btnUbah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbah1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        mode.setEditable(false);
        mode.setText("jTextField1");
        mode.setUI(null);
        mode.setFocusable(false);
        mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeActionPerformed(evt);
            }
        });

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Toko Buku Vero");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Master Buku");

        jLabel1.setText("ID");

        inputBukuId.setEditable(false);
        inputBukuId.setText("ID Buku");
        inputBukuId.setEnabled(false);
        inputBukuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBukuIdActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama");

        inputBukuNama.setText("Pemrograman Dasar");
        inputBukuNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBukuNamaActionPerformed(evt);
            }
        });

        inputBukuHarga.setText("80500");
        inputBukuHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBukuHargaActionPerformed(evt);
            }
        });

        jLabel5.setText("Harga, Rp.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(inputBukuId)
                                            .addComponent(inputBukuNama, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(inputBukuHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(inputBukuNama, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(inputBukuHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(inputBukuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addComponent(btnUbah)))
                    .addComponent(mode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    
    private void initTable() {
        tabel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabel.addColumn("Id");
        tabel.addColumn("Nama");
        tabel.addColumn("Harga");
        tabel.addColumn("Tgl Input");
        tabel.addColumn("Tgl Pembaharuan");
        tblBuku.setModel(tabel);
        tblBuku.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblBuku.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblBuku.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblBuku.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblBuku.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblBuku.getColumnModel().getColumn(4).setPreferredWidth(150);

    }

    private void showTable() {
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();
        dataBuku.clear();
        dataBuku = debe.tampil();
        for (int x = 0; x < dataBuku.size(); x++) {
            Object[] data = new Object[9];
            data[0] = dataBuku.get(x).getId();
            data[1] = dataBuku.get(x).getNama();
            data[2] = dataBuku.get(x).getHarga();
            data[3] = dataBuku.get(x).getCreatedAt();
            data[4] = dataBuku.get(x).getUpdatedAt();
            tabel.addRow(data);
        }
    }

    private void inputBukuIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBukuIdActionPerformed
    }//GEN-LAST:event_inputBukuIdActionPerformed

    private void inputBukuNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBukuNamaActionPerformed
    }//GEN-LAST:event_inputBukuNamaActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        operation("tblClick");
        System.out.println("klik table");

        int row = tblBuku.getSelectedRow();
        inputBukuId.setText(tblBuku.getModel().getValueAt(row, 0).toString());
        inputBukuNama.setText(tblBuku.getModel().getValueAt(row, 1).toString());
        inputBukuHarga.setText(tblBuku.getModel().getValueAt(row, 2).toString());

    }//GEN-LAST:event_tblBukuMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (mode.getText().equals("ubah")) {
            operation(null);
        } else {
            operation("ubah");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (mode.getText().equals("tambah")) {
            operation(null);
        } else {
            operation("tambah");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (inputIsEmpty()) {
            JOptionPane.showMessageDialog(null, "Inputan wajib dilengkapi!");
        } else {
            debe.setNama(inputBukuNama.getText());
            debe.setHarga(inputBukuHarga.getText());
            if (mode.getText().equals("tambah")) {
                debe.tambah();
            } else if (mode.getText().equals("ubah")) {
                debe.setId(inputBukuId.getText());
                debe.ubah();
            }
            showTable();
            operation(null);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblBuku.getSelectedRow();
        debe.setId(tblBuku.getModel().getValueAt(row, 0).toString());
        debe.hapus();
        inputClean();
        showTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void inputBukuHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBukuHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBukuHargaActionPerformed

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeActionPerformed

    private void btnUbah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbah1ActionPerformed
        // TODO add your handling code here:
        if (tblBuku.getRowCount() != 0) {
            new DbBuku().cetak();
        }
    }//GEN-LAST:event_btnUbah1ActionPerformed

    private void operation(String operation) {
        mode.setText(operation);
        if ("tambah".equals(mode.getText())) {
            btnTambah.setText("Batal");
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(true);
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(false);
            inputClean();
            inputEnable(true);
        } else if ("tblClick".equals(mode.getText())) {
            System.out.println("operation mode " + mode.getText());
            btnTambah.setText("Tambah");
            btnUbah.setText("Ubah");
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(false);
            btnHapus.setEnabled(true);
            btnUbah.setEnabled(true);
            inputEnable(false);
        } else if ("ubah".equals(mode.getText())) {
            btnUbah.setText("Batal");
            btnTambah.setEnabled(false);
            btnSimpan.setEnabled(true);
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(true);
            inputEnable(true);
        } else if (mode.getText().isEmpty()) {
            btnTambah.setText("Tambah");
            btnUbah.setText("Ubah");
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(false);
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(false);
            inputClean();
            inputEnable(false);
        }
    }

    private boolean inputIsEmpty() {
        boolean empty = false;
        if (inputBukuNama.getText().isEmpty() || inputBukuHarga.getText().isEmpty()) {
            empty = true;
        }
        return empty;

    }

    private void inputEnable(boolean x) {
        inputBukuNama.setEnabled(x);
        inputBukuHarga.setEnabled(x);
    }

    private void inputClean() {
        inputBukuId.setText(null);
        inputBukuNama.setText(null);
        inputBukuHarga.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterBuku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterBuku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterBuku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterBuku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnUbah1;
    private javax.swing.JTextField inputBukuHarga;
    private javax.swing.JTextField inputBukuId;
    private javax.swing.JTextField inputBukuNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mode;
    private javax.swing.JTable tblBuku;
    // End of variables declaration//GEN-END:variables
}
