/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobukuvero;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Az
 */
public class MasterPembeli extends javax.swing.JFrame {

    DefaultTableModel tabel;
    DbPembeli debe = new DbPembeli();
    List<DbPembeli> dataBuku = new ArrayList<>();

    /**
     * Creates new form MasterPembeli
     */
    public MasterPembeli() {
        initComponents();
        initTable();
        showTable();
        // Mode Operasi CRUD untuk tampilan
        operation(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        inputPembeliId = new javax.swing.JTextField();
        inputPembeliNama = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        mode.setEditable(false);
        mode.setText("jTextField1");
        mode.setUI(null);
        mode.setFocusable(false);

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Toko Buku Vero");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Master Pembeli");

        jLabel1.setText("ID Pembeli");

        inputPembeliId.setEditable(false);
        inputPembeliId.setText("ID Pembeli");
        inputPembeliId.setEnabled(false);
        inputPembeliId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPembeliIdActionPerformed(evt);
            }
        });

        inputPembeliNama.setText("Nama Pembeli");
        inputPembeliNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPembeliNamaActionPerformed(evt);
            }
        });

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel2.setText("Nama Pembeli");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnUbah))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputPembeliNama)
                                    .addComponent(inputPembeliId))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputPembeliNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(inputPembeliId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTambah)
                            .addComponent(btnSimpan)
                            .addComponent(btnHapus)
                            .addComponent(btnUbah)))
                    .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    
    private void initTable() {
        tabel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabel.addColumn("Id");
        tabel.addColumn("Nama");
        tabel.addColumn("Tgl Input");
        tabel.addColumn("Tgl Pembaharuan");
        tblBuku.setModel(tabel);
        tblBuku.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblBuku.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblBuku.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblBuku.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblBuku.getColumnModel().getColumn(3).setPreferredWidth(150);
    }

    private void showTable() {
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();
        dataBuku.clear();
        dataBuku = debe.tampil();
        for (int x = 0; x < dataBuku.size(); x++) {
            Object[] data = new Object[9];
            data[0] = dataBuku.get(x).getId();
            data[1] = dataBuku.get(x).getNama();
            data[2] = dataBuku.get(x).getCreatedAt();
            data[3] = dataBuku.get(x).getUpdatedAt();
            tabel.addRow(data);
        }
    }

    private void inputPembeliIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPembeliIdActionPerformed
    }//GEN-LAST:event_inputPembeliIdActionPerformed

    private void inputPembeliNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPembeliNamaActionPerformed
    }//GEN-LAST:event_inputPembeliNamaActionPerformed

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        operation("tblClick");
        System.out.println("klik table");

        int row = tblBuku.getSelectedRow();
        inputPembeliId.setText(tblBuku.getModel().getValueAt(row, 0).toString());
        inputPembeliNama.setText(tblBuku.getModel().getValueAt(row, 1).toString());
    }//GEN-LAST:event_tblBukuMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        if (mode.getText().equals("ubah")) {
            operation(null);
        } else {
            operation("ubah");
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        if (mode.getText().equals("tambah")) {
            operation(null);
        } else {
            operation("tambah");
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (inputIsEmpty()) {
            JOptionPane.showMessageDialog(null, "Inputan wajib dilengkapi!");
        } else {
            debe.setNama(inputPembeliNama.getText());
            if (mode.getText().equals("tambah")) {
                debe.tambah();
            } else if (mode.getText().equals("ubah")) {
                debe.setId(inputPembeliId.getText());
                debe.ubah();
            }
            showTable();
            operation(null);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblBuku.getSelectedRow();
        debe.setId(tblBuku.getModel().getValueAt(row, 0).toString());
        debe.hapus();
        inputClean();
        showTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void operation(String operation) {
        mode.setText(operation);
        if ("tambah".equals(mode.getText())) {
            btnTambah.setText("Batal");
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(true);
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(false);
            inputClean();
            inputEnable(true);
        } else if ("tblClick".equals(mode.getText())) {
            System.out.println("operation mode " + mode.getText());
            btnTambah.setText("Tambah");
            btnUbah.setText("Ubah");
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(false);
            btnHapus.setEnabled(true);
            btnUbah.setEnabled(true);
            inputEnable(false);
        } else if ("ubah".equals(mode.getText())) {
            btnUbah.setText("Batal");
            btnTambah.setEnabled(false);
            btnSimpan.setEnabled(true);
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(true);
            inputEnable(true);
        } else if (mode.getText().isEmpty()) {
            btnTambah.setText("Tambah");
            btnUbah.setText("Ubah");
            btnTambah.setEnabled(true);
            btnSimpan.setEnabled(false);
            btnHapus.setEnabled(false);
            btnUbah.setEnabled(false);
            inputClean();
            inputEnable(false);
        }
    }

    private boolean inputIsEmpty() {
        boolean empty = false;
        if (inputPembeliNama.getText().isEmpty()) {
            empty = true;
        }
        return empty;

    }

    private void inputEnable(boolean x) {
        inputPembeliNama.setEnabled(x);
    }

    private void inputClean() {
        inputPembeliId.setText(null);
        inputPembeliNama.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterPembeli.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterPembeli.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterPembeli.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterPembeli.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputPembeliId;
    private javax.swing.JTextField inputPembeliNama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mode;
    private javax.swing.JTable tblBuku;
    // End of variables declaration//GEN-END:variables
}
