/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobukuvero;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Az
 */
public class TambahPembelian extends javax.swing.JFrame {

    String PembeliId, BukuId;
    DefaultTableModel tabelPembeli, tabelBuku, tabelBukuDetail;
    DbPembeli debePembeli = new DbPembeli();
    List<DbPembeli> dataPembeli = new ArrayList<>();
    DbBuku debeBuku = new DbBuku();
    List<DbBuku> dataBuku = new ArrayList<>();
    DbPembelian debePembelian = new DbPembelian();
    DbDetailPembelian debeDetailPembelian = new DbDetailPembelian();

    /**
     * Creates new form MasterPembeli
     */
    public TambahPembelian() {
        initComponents();
        // Mode Operasi CRUD untuk tampilan
        operation(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogPembeli = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPembeli = new javax.swing.JTable();
        btnPilihPembeli = new javax.swing.JButton();
        btnBatalDialogPembeli = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dialogBuku = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBukuDialog = new javax.swing.JTable();
        btnPilihPembeli1 = new javax.swing.JButton();
        btnBatalDialogBuku = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        inputPembeliId = new javax.swing.JTextField();
        btnCariPembeli = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        inputPembeliNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        inputBukuId = new javax.swing.JTextField();
        btnCariBuku = new javax.swing.JButton();
        inputBukuNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        inputPembelianTanggal = new com.toedter.calendar.JDateChooser();
        btnTambahBuku = new javax.swing.JButton();
        btnHapusBuku = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        inputBukuHarga = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();

        dialogPembeli.setMinimumSize(new java.awt.Dimension(532, 311));

        tblPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPembeli);

        btnPilihPembeli.setText("Pilih Pembeli");
        btnPilihPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihPembeliActionPerformed(evt);
            }
        });

        btnBatalDialogPembeli.setText("Batal");
        btnBatalDialogPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalDialogPembeliActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Toko Buku Vero");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Data Pembeli");

        javax.swing.GroupLayout dialogPembeliLayout = new javax.swing.GroupLayout(dialogPembeli.getContentPane());
        dialogPembeli.getContentPane().setLayout(dialogPembeliLayout);
        dialogPembeliLayout.setHorizontalGroup(
            dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembeliLayout.createSequentialGroup()
                .addGroup(dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogPembeliLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(dialogPembeliLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12))))
                    .addGroup(dialogPembeliLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                            .addGroup(dialogPembeliLayout.createSequentialGroup()
                                .addComponent(btnPilihPembeli)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBatalDialogPembeli)))))
                .addContainerGap())
        );
        dialogPembeliLayout.setVerticalGroup(
            dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogPembeliLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogPembeliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilihPembeli)
                    .addComponent(btnBatalDialogPembeli))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblBukuDialog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblBukuDialog);

        btnPilihPembeli1.setText("Pilih Buku");
        btnPilihPembeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihPembeli1ActionPerformed(evt);
            }
        });

        btnBatalDialogBuku.setText("Batal");
        btnBatalDialogBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalDialogBukuActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Toko Buku Vero");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Data Buku");

        javax.swing.GroupLayout dialogBukuLayout = new javax.swing.GroupLayout(dialogBuku.getContentPane());
        dialogBuku.getContentPane().setLayout(dialogBukuLayout);
        dialogBukuLayout.setHorizontalGroup(
            dialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogBukuLayout.createSequentialGroup()
                .addGroup(dialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogBukuLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel13))
                    .addGroup(dialogBukuLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel14))
                    .addGroup(dialogBukuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(dialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                            .addGroup(dialogBukuLayout.createSequentialGroup()
                                .addComponent(btnPilihPembeli1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBatalDialogBuku)))))
                .addContainerGap())
        );
        dialogBukuLayout.setVerticalGroup(
            dialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogBukuLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(dialogBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPilihPembeli1)
                    .addComponent(btnBatalDialogBuku))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Toko Buku Vero");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tambah Pembelian");

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Pembeli");

        inputPembeliId.setEditable(false);
        inputPembeliId.setToolTipText("ID Pembeli");
        inputPembeliId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPembeliIdActionPerformed(evt);
            }
        });

        btnCariPembeli.setText("Pilih Pembeli");
        btnCariPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariPembeliActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama Pembeli");

        inputPembeliNama.setEditable(false);
        inputPembeliNama.setToolTipText("Nama Pembeli");
        inputPembeliNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPembeliNamaActionPerformed(evt);
            }
        });

        jLabel6.setText("Tanggal Pembelian");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Data Pembeli");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Data Pembelian Buku");

        jLabel9.setText("ID Buku");

        inputBukuId.setEditable(false);
        inputBukuId.setToolTipText("ID Buku");
        inputBukuId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBukuIdActionPerformed(evt);
            }
        });

        btnCariBuku.setText("Pilih Buku");
        btnCariBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariBukuActionPerformed(evt);
            }
        });

        inputBukuNama.setEditable(false);
        inputBukuNama.setToolTipText("Nama Buku");
        inputBukuNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBukuNamaActionPerformed(evt);
            }
        });

        jLabel10.setText("Nama Buku");

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "-"
            }
        ));
        jScrollPane1.setViewportView(tblBuku);

        inputPembelianTanggal.setDateFormatString("yyyy-MM-dd");

        btnTambahBuku.setText("Tambah Pembelian Buku");
        btnTambahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahBukuActionPerformed(evt);
            }
        });

        btnHapusBuku.setText("Hapus Pembelian Buku");
        btnHapusBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusBukuActionPerformed(evt);
            }
        });

        jLabel15.setText("Harga Buku");

        inputBukuHarga.setEditable(false);
        inputBukuHarga.setToolTipText("Nama Buku");
        inputBukuHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputBukuHargaActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotal.setText("TOTAL Rp. 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputBukuId, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputBukuNama, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputBukuHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnTambahBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapusBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputPembelianTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel4)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(inputPembeliId, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCariPembeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(inputPembeliNama))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCariPembeli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(inputPembeliId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPembeliNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputPembelianTanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(btnCariBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputBukuId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBukuNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBukuHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahBuku)
                    .addComponent(btnHapusBuku))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed

    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        if (inputPembeliId.getText().isEmpty() || inputPembelianTanggal.getDate() == null || tblBuku.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Semua inputan wajib diisi");
        } else {
            DateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
            String date = fmt.format(inputPembelianTanggal.getDate()); //jdatechooser
            //simpan ke tabel peminjaman
            debePembelian.setPembeliId(inputPembeliId.getText());
            debePembelian.setTanggal(date);
            debePembelian.tambah();
            //simpan ke tabel peminjaman detail
            for (int x = 0; x < tblBuku.getRowCount(); x++) {
                debeDetailPembelian.setPembelianId(debePembelian.ambilIdTerakhir());
                debeDetailPembelian.setBukuId(tblBuku.getValueAt(x, 0).toString());
                debeDetailPembelian.tambah();
            }
            JOptionPane.showMessageDialog(null, "Simpan peminjaman Berhasil");
            dispose();
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnCariPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariPembeliActionPerformed
        initTablePembeli();
        showTablePembeli();
        dialogPembeli.setSize(532, 350);
        dialogPembeli.setLocationRelativeTo(this);
        dialogPembeli.setVisible(true);
    }//GEN-LAST:event_btnCariPembeliActionPerformed

    private void inputPembeliIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPembeliIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPembeliIdActionPerformed

    private void inputPembeliNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPembeliNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPembeliNamaActionPerformed

    private void inputBukuIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBukuIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBukuIdActionPerformed

    private void btnCariBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariBukuActionPerformed
        initTableBukuDialog();
        showTableBukuDialog();
        dialogBuku.setSize(532, 350);
        dialogBuku.setLocationRelativeTo(this);
        dialogBuku.setVisible(true);
    }//GEN-LAST:event_btnCariBukuActionPerformed

    private void inputBukuNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBukuNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBukuNamaActionPerformed

    private void btnPilihPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihPembeliActionPerformed
        // TODO add your handling code here:
        int row = tblPembeli.getSelectedRow();
        PembeliId = tblPembeli.getValueAt(row, 0).toString();
        inputPembeliId.setText(tblPembeli.getValueAt(row, 0).toString());
        inputPembeliNama.setText(tblPembeli.getValueAt(row, 1).toString());
        dialogPembeli.setVisible(false);
    }//GEN-LAST:event_btnPilihPembeliActionPerformed

    private void btnBatalDialogPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalDialogPembeliActionPerformed
        dialogPembeli.setVisible(false);
    }//GEN-LAST:event_btnBatalDialogPembeliActionPerformed

    private void btnPilihPembeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihPembeli1ActionPerformed
        // TODO add your handling code here:
        int row = tblBukuDialog.getSelectedRow();
        BukuId = tblBukuDialog.getValueAt(row, 0).toString();
        inputBukuId.setText(tblBukuDialog.getValueAt(row, 0).toString());
        inputBukuNama.setText(tblBukuDialog.getValueAt(row, 1).toString());
        inputBukuHarga.setText(tblBukuDialog.getValueAt(row, 2).toString());
        dialogBuku.setVisible(false);
    }//GEN-LAST:event_btnPilihPembeli1ActionPerformed

    private void btnBatalDialogBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalDialogBukuActionPerformed
        dialogBuku.setVisible(false);
    }//GEN-LAST:event_btnBatalDialogBukuActionPerformed

    private void btnTambahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahBukuActionPerformed
        if (inputBukuId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Buku wajib dipilih!");
        } else {
            if (tblBuku.getRowCount() == 0) {
                initTableBuku();
            }
            // Validasi buku sama belum perlu
            Object[] data = new Object[3];
            data[0] = inputBukuId.getText();
            data[1] = inputBukuNama.getText();
            data[2] = inputBukuHarga.getText();
            tabelBukuDetail.addRow(data);
            kalkulasiHarga();
            BukuId = null;
            inputBukuId.setText(null);
            inputBukuNama.setText(null);
            inputBukuHarga.setText(null);

        }
    }//GEN-LAST:event_btnTambahBukuActionPerformed

    private void kalkulasiHarga() {
        //simpan ke tabel peminjaman detail
        int hargaTotal = 0;
        for (int x = 0; x < tblBuku.getRowCount(); x++) {
            hargaTotal += Integer.parseInt(tblBuku.getValueAt(x, 2).toString());
        }
        lblTotal.setText("TOTAL Rp. " + hargaTotal);
    }

    private void btnHapusBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusBukuActionPerformed
        if (tblBuku.getRowCount() != 0) {
            tabelBukuDetail.removeRow(tblBuku.getSelectedRow());
            kalkulasiHarga();
        }
    }//GEN-LAST:event_btnHapusBukuActionPerformed

    private void inputBukuHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputBukuHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputBukuHargaActionPerformed

    private void initTablePembeli() {
        tabelPembeli = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabelPembeli.addColumn("Id");
        tabelPembeli.addColumn("Nama");
        tblPembeli.setModel(tabelPembeli);
        //Untuk mengatur lebar kolom
        tblPembeli.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPembeli.getColumnModel().getColumn(0).setPreferredWidth(100);
        tblPembeli.getColumnModel().getColumn(1).setPreferredWidth(300);
    }

    private void showTablePembeli() {
        tabelPembeli.getDataVector().removeAllElements();
        tabelPembeli.fireTableDataChanged();
        dataPembeli.clear();
        dataPembeli = debePembeli.tampil();
        for (int x = 0; x < dataPembeli.size(); x++) {
            Object[] data = new Object[9];
            data[0] = dataPembeli.get(x).getId();
            data[1] = dataPembeli.get(x).getNama();
            tabelPembeli.addRow(data);
        }
    }

    private void initTableBukuDialog() {
        tabelBuku = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabelBuku.addColumn("Id");
        tabelBuku.addColumn("Nama");
        tabelBuku.addColumn("Harga");
        tblBukuDialog.setModel(tabelBuku);
        //Untuk mengatur lebar kolom
        tblBukuDialog.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblBukuDialog.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblBukuDialog.getColumnModel().getColumn(1).setPreferredWidth(250);
        tblBukuDialog.getColumnModel().getColumn(2).setPreferredWidth(200);

    }

    private void showTableBukuDialog() {
        tabelBuku.getDataVector().removeAllElements();
        tabelBuku.fireTableDataChanged();
        dataBuku.clear();
        dataBuku = debeBuku.tampil();
        for (int x = 0; x < dataBuku.size(); x++) {
            Object[] data = new Object[3];
            data[0] = dataBuku.get(x).getId();
            data[1] = dataBuku.get(x).getNama();
            data[2] = dataBuku.get(x).getHarga();
            tabelBuku.addRow(data);
        }
    }

    private void initTableBuku() {
        tabelBukuDetail = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabelBukuDetail.addColumn("Buku ID");
        tabelBukuDetail.addColumn("Judul");
        tabelBukuDetail.addColumn("Harga");
        tblBuku.setModel(tabelBukuDetail);
    }

    private void operation(String operation) {
    }

    private boolean inputIsEmpty() {
        return false;
//        boolean empty = false;
//        if (inputPembeliNama.getText().isEmpty()) {
//            empty = true;
//        }
//        return empty;
    }

    private void inputEnable(boolean x) {
//        inputPembeliNama.setEnabled(x);
    }

    private void inputClean() {
        inputPembeliId.setText(null);
//        inputPembeliNama.setText(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatalDialogBuku;
    private javax.swing.JButton btnBatalDialogPembeli;
    private javax.swing.JButton btnCariBuku;
    private javax.swing.JButton btnCariPembeli;
    private javax.swing.JButton btnHapusBuku;
    private javax.swing.JButton btnPilihPembeli;
    private javax.swing.JButton btnPilihPembeli1;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambahBuku;
    private javax.swing.JDialog dialogBuku;
    private javax.swing.JDialog dialogPembeli;
    private javax.swing.JTextField inputBukuHarga;
    private javax.swing.JTextField inputBukuId;
    private javax.swing.JTextField inputBukuNama;
    private javax.swing.JTextField inputPembeliId;
    private javax.swing.JTextField inputPembeliNama;
    private com.toedter.calendar.JDateChooser inputPembelianTanggal;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTable tblBukuDialog;
    private javax.swing.JTable tblPembeli;
    // End of variables declaration//GEN-END:variables
}
