/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tokobukuvero;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Az
 */
public class TransaksiPembelian extends javax.swing.JFrame {

    DefaultTableModel tabel;
    DbPembelian debe = new DbPembelian();
    List<DbPembelian> dataPembelian = new ArrayList<>();
    DefaultTableModel tabelDetail;
    DbDetailPembelian debeDetail = new DbDetailPembelian();
    List<DbDetailPembelian> dataDetail = new ArrayList<>();

    /**
     * Creates new form TransaksiPembelian
     */
    public TransaksiPembelian() {
        initComponents();
        initTable();
        showTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogDetail = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetailPembelian = new javax.swing.JTable();
        mode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembelian = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnRincian = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Toko Buku Vero");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Master Pembeli");

        tblDetailPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tblDetailPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDetailPembelianMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDetailPembelian);

        javax.swing.GroupLayout dialogDetailLayout = new javax.swing.GroupLayout(dialogDetail.getContentPane());
        dialogDetail.getContentPane().setLayout(dialogDetailLayout);
        dialogDetailLayout.setHorizontalGroup(
            dialogDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dialogDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dialogDetailLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel5))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dialogDetailLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dialogDetailLayout.setVerticalGroup(
            dialogDetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogDetailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        mode.setEditable(false);
        mode.setText("jTextField1");
        mode.setUI(null);
        mode.setFocusable(false);
        mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeActionPerformed(evt);
            }
        });

        tblPembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1"
            }
        ));
        tblPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembelian);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Toko Buku Vero");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Transaksi Pembelian");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Muat Ulang");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnRincian.setText("Rincian");
        btnRincian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRincianActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRincian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnTambah)
                        .addComponent(btnHapus)
                        .addComponent(btnRefresh)
                        .addComponent(btnRincian)
                        .addComponent(btnCetak))
                    .addComponent(mode, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//    
    private void initTable() {
        tabel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabel.addColumn("Id");
        tabel.addColumn("Nama");
        tabel.addColumn("Tgl Pembelian");
        tabel.addColumn("Tgl Pembaharuan");
        tabel.addColumn("Tgl Pembaharuan");
        tblPembelian.setModel(tabel);
        tblPembelian.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPembelian.getColumnModel().getColumn(0).setPreferredWidth(50);
        tblPembelian.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblPembelian.getColumnModel().getColumn(2).setPreferredWidth(150);
        tblPembelian.getColumnModel().getColumn(3).setPreferredWidth(150);
        tblPembelian.getColumnModel().getColumn(4).setPreferredWidth(150);
    }

    private void showTable() {
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();
        dataPembelian.clear();
        dataPembelian = debe.tampil();
        for (int x = 0; x < dataPembelian.size(); x++) {
            Object[] data = new Object[9];
            data[0] = dataPembelian.get(x).getId();
            data[1] = dataPembelian.get(x).getNama();
            data[2] = dataPembelian.get(x).getTanggal();
            data[3] = dataPembelian.get(x).getCreatedAt();
            data[4] = dataPembelian.get(x).getUpdatedAt();
            tabel.addRow(data);
        }
    }

    private void initTableDetailPembelian() {
        tabelDetail = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tabelDetail.addColumn("Nama Buku");
        tabelDetail.addColumn("Harga");
        tabelDetail.addColumn("Tgl Pembelian");
        tblDetailPembelian.setModel(tabelDetail);
        tblDetailPembelian.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblDetailPembelian.getColumnModel().getColumn(0).setPreferredWidth(200);
        tblDetailPembelian.getColumnModel().getColumn(1).setPreferredWidth(150);
        tblDetailPembelian.getColumnModel().getColumn(2).setPreferredWidth(150);
    }

    private void tblPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembelianMouseClicked
        // delete
    }//GEN-LAST:event_tblPembelianMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        new TambahPembelian().setVisible(true);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int row = tblPembelian.getSelectedRow();
        debe.setId(tblPembelian.getModel().getValueAt(row, 0).toString());
        debe.hapus();
        showTable();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        showTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeActionPerformed

    private void tblDetailPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDetailPembelianMouseClicked
        // table di dialog
    }//GEN-LAST:event_tblDetailPembelianMouseClicked

    private void btnRincianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRincianActionPerformed
        // TODO add your handling code here:
        if (tblPembelian.getRowCount() != 0) {
            initTableDetailPembelian();
            tabelDetail.getDataVector().removeAllElements();
            tabelDetail.fireTableDataChanged();
            dataDetail.clear();
            System.out.println(tblPembelian.getValueAt(tblPembelian.getSelectedRow(), 0).toString());
            dataDetail = debeDetail.tampil(tblPembelian.getValueAt(tblPembelian.getSelectedRow(), 0).toString());
            for (int x = 0; x < dataDetail.size(); x++) {
                Object[] dataDt = new Object[3];
                dataDt[0] = dataDetail.get(x).getNama();
                dataDt[1] = dataDetail.get(x).getHarga();
                dataDt[2] = dataDetail.get(x).getTanggal();
                tabelDetail.addRow(dataDt);
            }
            dialogDetail.setSize(589, 276);
            dialogDetail.setLocationRelativeTo(this);
            dialogDetail.setVisible(true);
        }
    }//GEN-LAST:event_btnRincianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransaksiPembelian.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransaksiPembelian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRincian;
    private javax.swing.JButton btnTambah;
    private javax.swing.JDialog dialogDetail;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField mode;
    private javax.swing.JTable tblDetailPembelian;
    private javax.swing.JTable tblPembelian;
    // End of variables declaration//GEN-END:variables
}
